### ISSUE TITLE
Hard crash when selecting the first subclass for gatherer (herbmaster telegatherer)

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#102]

**Comment by MNoya** [comment]
Couldn't reproduce but added an extra check for never SetModel'ing to a nil path

**Comment by Vendivar** [comment]
Shaman does have a pet I believe.

**Comment by Vendivar** [comment]
This bug has been fixed afaik. I've been doing testing on most classes and haven't had this problem (been using herb master for some time)
