### ISSUE TITLE
Scrolling in the crafting window moves the heroes camera up and down.

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#106]
Thinking of disabling that part of the camera if possible.

**Comment by MNoya** [comment]
I managed to prevent this in ETD by keeping a global which gets changed onmouseout / onmouseover, it's easy to fix

**Comment by MNoya** [comment]
Attempted a fix, need confirmation if its still having problems. I added a bunch of debug messages on the scrolling/mouseovering events

**Comment by Dli42** [comment]
I'm still getting the same issue, with the craft screen open and my mouse over it both the menu and the game scrolls

**Comment by Vendivar** [comment]
You had to click the crafting window apparently. Auto focus will be added
soon so you won't have to

**Comment by Vendivar** [comment]
@MNoya Can we get an auto focus on that window when its toggled?

**Comment by Nooobody** [comment]
The crafting menu should now auto-focus. But when you exit the menu, you have to click the game world to be able to zoom. I also added the focus on building crafting menus, however it's not perfect on those.
