### ISSUE TITLE
Bush Timing is way off

### ISSUE THREAD

**Issue by MNoya** [Vendivar/IslandTrollTribes2#109]
It's like every bush takes 10 minutes to spawn their first item

**Comment by Dli42** [comment]
The timing can be adjusted, but the 300 seconds from before is way too long.

**Comment by Vendivar** [comment]
Agreed the timing is off. I know I set it to spawn the first item around
the end of noob time but thereafter it should be frequent

**Comment by Dli42** [comment]
I changed bush spawning to be every 60 seconds. Should I make it 300 seconds for the first spawning and 60 after that?

**Comment by MNoya** [comment]
To expand on this: Do you guys think the bushes should glow white all the time? We could use that effect to show the bush actually has items inside, instead of needing to check empty bushes all through the game

**Comment by Vendivar** [comment]
Every 60 seconds is fine. I don't think any more changes are needed except
making  it not every 60 seconds garutnteed.

**Comment by MNoya** [comment]
Added bush glow only while the bushes have items in 88a5acabc86237773a8dcc0359e748bc89ba7378
