### ISSUE TITLE
Spawning is too slow

### ISSUE THREAD

**Issue by dsrubin** [Vendivar/IslandTrollTribes2#11]
I haven't seen any spawning code yet but its really slow

**Comment by MNoya** [comment]
I increased the spawn think time from 120 to 20, the Max still applies but it reaches it way faster now.

Would like some insight on what is supposed to be a good spawn rate / amount for the map

**Comment by EdibleEd** [comment]
The values are pulled from ITT1 so that is surprising, might be that the map is larger.

**Comment by dsrubin** [comment]
Imo: ideally there should be a large burst of spawning initially, then spawning should slow down. We don't want to hit animal/item cap in the first 5 minutes, but we also don't want a barren map during the early stages.
