### ISSUE TITLE
Small stairs make it hard for big teams to go through

### ISSUE THREAD

**Issue by MNoya** [Vendivar/IslandTrollTribes2#113]
Making it possible for 1 guy to completely cock-block his team

**Comment by muhshi4** [comment]
Narrow paths allow for strategic blocking though, which is a big part of itt.

**Comment by Vendivar** [comment]
So what is the exact complaint

**Comment by muhshi4** [comment]
By removing the small stairs and narrow paths you make it hard to use blocking as a mechanic, which imo should stay in the game. You shouldnt change something because a teammate is doing somthing stupid

**Comment by MNoya** [comment]
Fair enough, just wanted to point it out as there seems to be an abundance of these on the current map near the places that will be used to build bases

**Comment by Vendivar** [comment]
That's fine. FYI  Please use professional terms on github such as "this
would be detrimental to game play" instead of stupid.
