### ISSUE TITLE
Map Settings

### ISSUE THREAD

**Issue by MNoya** [Vendivar/IslandTrollTribes2#125]
Currently we only have 1 map for 12 players named `islantrolltribesa8`

I think the best setting would be to provide:

* 9 players 3 team map as the default go-to option: 3v3v3
* 16 players 4 team map which can be used for any combination of 3 or 4 player team games
  * Teams could be of 5 players, to allow for 5v5 (is this a desirable combination? Otherwise we should also do a 10 player 2 team map most likely)

**Comment by MNoya** [comment]
Map names should be `itt_trio` and `itt_quad`, I couldn't build because the map is filling my RAM in under 30 seconds.

**Comment by Dli42** [comment]
Me and Internet Vet actually noticed this, if the map is named anything other than islandtrolltribesa8 it will cause a memory leak.

I have no idea why, but it's been like this for a long time now, hence the version number being stuck on a8

**Comment by Vendivar** [comment]
Oh really? I'll try it when I'm home to confirm.

**Comment by Dli42** [comment]
Maybe it was Toxic Ninja back in the day. I definitely remember it happening. If you try to compile a differently named version of the same map ram usage shoots up to full and fucks your computer up.

**Comment by Vendivar** [comment]
I thought it was amanite
