### ISSUE TITLE
items still get stuck under water herb bushes, mushroom bushes seem fine tho

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#130]

**Comment by MNoya** [comment]
You mean they are hard/impossible to click, due to hitbox, right?

**Comment by Vendivar** [comment]
May just need to alter the number value for preventing item spawning around
bushes

**Comment by muhshi4** [comment]
Yeah, its impossible to click the item if you place it on the water herb bush. But its impossible to get items stuck under the mushroom bushes. Maybe there's a way to change the hitbox to the same as the mushroom bush? 

Preventing items spawning around the bushes solves a part of the problem. But in a scenario where im running away from an enemy and i know im going to die, i could just throw all my gear onto a water herb bush and effectively deny him from getting any loot. 

Maybe make the herb bushes able to pick up items like the buildings? that would make you able to pick  up the items with the herb bush and then transfer them to you.

**Comment by MNoya** [comment]
@Vendivar just edit the hitboxes to be smaller with your cube method and this should be fixed

**Comment by Vendivar** [comment]
On it
