### ISSUE TITLE
disease might be crashing the game.

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#140]
Was playing as a gatherer and fighting a hunter, used disease potion on him and the game crashed a few seconds later. Might've been something else tho

**Comment by Dli42** [comment]
I'll check it out and see if I can reproduce it

**Comment by muhshi4** [comment]
we actually tried it again and it didn't work, might've been something else.

**Comment by Dli42** [comment]
I can't reproduce it from testing in single player. Have you seen it happen again in a live lobby?

**Comment by Dli42** [comment]
I don't think Disease Potions are the problem, so I'm closing this.
