### ISSUE TITLE
i broke the craft menu

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#143]
http://imgur.com/GpiqwKX

http://imgur.com/vsZqGeF

-can't remove items from armory by dragging

-can't see any icons in craftmenu and sleepmenu

**Comment by MNoya** [comment]
Any way to reproduce it?

**Comment by Vendivar** [comment]
Did you alt tab from the game?

**Comment by muhshi4** [comment]
yeah i think i alt tabbed before this.
