### ISSUE TITLE
Chicken flea attack aura is suppose to bounce

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#147]

**Comment by muhshi4** [comment]
nvm i was wrong it doesn't bounce https://www.youtube.com/watch?v=NLULxSXt_jU here's how it looks in wc3.
-doesn't attack priests with anti magic shield
-attacks random buildings
-besides the flea aura attack chicken has a really slow normal attack for chopping trees

**Comment by MNoya** [comment]
Magic immunity interacion and random building attack will be done. 

Is Chop tree attack really necessary?

**Comment by muhshi4** [comment]
nope, that was only for attacking fake trees but i don't think those exist in dota 2 itt

**Comment by MNoya** [comment]
Got it, thanks for the insight!
