### ISSUE TITLE
Omni Tower doesnt spend charges on item in its inventory on use.

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#148]
Has to do with passing a copy of the item to the dummy.

**Comment by muhshi4** [comment]
also doesn't auto attack animals, you have to select the tower and target the animal yourself.

**Comment by MNoya** [comment]
@muhshi4 that's probably the same with #137 you need to change your autoattack settings for towers to auto-attack enemies. I can add autoattack logic to the tower if needed though
