### ISSUE TITLE
Thief Medallion not consumed after use (LoL)

### ISSUE THREAD

**Issue by Dillerfax** [Vendivar/IslandTrollTribes2#150]

**Comment by Vendivar** [comment]
Yeah I just noticed that too. I'll fix it real quick.

**Comment by muhshi4** [comment]
and unlimited range :DDDD

**Comment by MNoya** [comment]
Oops, wrong closed issue

**Comment by Dillerfax** [comment]
And i think the passive ability of Thief Medallion is not working too.

**Comment by Dli42** [comment]
I'm working on the passive effect now
