### ISSUE TITLE
Victory conditions sometimes fail

### ISSUE THREAD

**Issue by Dli42** [Vendivar/IslandTrollTribes2#152]
May be because one player is still on character select on a third team

**Comment by MNoya** [comment]
The win condition should be; all heroes alive are on the same team.

**Comment by MNoya** [comment]
Update: I reviewed this and I have no idea why it would fail. You guys are certain the test version is up to date? The current `ITT:WinConditionThink()` is using `HeroList:GetAllHeroes()` which shouldn't return unpicked hero-players as far as I know.

**Comment by Vendivar** [comment]
We also had some disconnected players

**Comment by Dli42** [comment]
Vet had just updated it before we played. 2 players on my team were afk, but still in game and the lone player on team 3 never picked character. We can try to replicate this in multiplayer later.
