### ISSUE TITLE
Scrolling still buggy on craft panels and inworld

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#154]

**Comment by MNoya** [comment]
Could've sworn I got it right this time. Where is it failing in particular?

**Comment by Vendivar** [comment]
It's failing both in world and on the crafting menu (no change).

**Comment by MNoya** [comment]
Can't reproduce. Works perfectly on my end. Maybe a resolution issue? I'm using 16:9

**Comment by Dli42** [comment]
Scrolling is fine here 16:10 res.

It's kind of annoying that it scrolls both the game camera and the menu, though

**Comment by MNoya** [comment]
It doesn't scroll both for me, that's what I'm saying. I can prove it with a video :laughing:

**Comment by Dli42** [comment]
I wonder why it's not working on our machines. Changing resolutions didn't help at all, nor did changing from windowed to windowed borderless

**Comment by muhshi4** [comment]
scrolling has worked fine in all the beta games i've played, im on 16:9 resolution

**Comment by MNoya** [comment]
Reopened  #106
