### ISSUE TITLE
Panorama process out of memory with last patch

### ISSUE THREAD

**Issue by MNoya** [Vendivar/IslandTrollTribes2#155]
Probably something wrong with the engine but will keep this issue open in case we find any way to work around it.

**Comment by Dli42** [comment]
So this started happening after a few restarts during testing

http://i.imgur.com/tZsWvWu.png

**Comment by Vendivar** [comment]
So I tested the mod version that was posted 3 days ago and theres no lag problem at all. I think it was something we did in the last 3 days.

I redid some recipes and skipped some numbers, I will try to redo the numbering and see if that does it for some reason.

**Comment by Dli42** [comment]
Mix Herbs on the herbmaster telegatherer used to just lag really bad but now it instantly runs out of memory

http://i.imgur.com/hxoWj8A.png

**Comment by Vendivar** [comment]
For the record I used the panorama folder from this commit https://github.com/Vendivar/IslandTrollTribes2/commit/ef95a22f4daea738519836132c1c1c55a2887223

and everything was pretty smooth so i say we start there

**Comment by Dli42** [comment]
I think I tracked it down to this commit: 74da6558831a4a7e004071e4795d849a0c185eb7

We still have other memory leak issues but this one is causing me to crash after just 5 restarts.

**Comment by MNoya** [comment]
The problem might be how I count the tips then. It's weird because I count them in the same way in eletd (an infinite loop which breaks at the first non-localized string)

**Comment by Dli42** [comment]
So I jumped the gun before, it wasn't actually the tips at all. It's this commit between the tips getting added: a84104211c67c7dd02c2fdfd4d01869d95ee21a8

I am confident this is where it all went to hell. Something is really wrong with the mixing pot/mix herbs menu.

**Comment by MNoya** [comment]
I just downloaded [a 1-month old version](https://github.com/Vendivar/IslandTrollTribes2/tree/4e04993c9d4101bb2c8992c0ba7af074a66fd243) and I still encounter the `Assertion Failed in function V8FatalErrorHandler()` when rebuilding the UI ingame.
