### ISSUE TITLE
Toggle Shapeshifter abilities need to toggle only one ability at a time. 

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#160]
If any other one is toggled off except the true form it needs to toggle on true form as well.

**Comment by Vendivar** [comment]
Okay I have it set up- so that each ability can only be toggled one at a time but id prefer that when any of the 3 are toggled off that true form becomes toggled on. Additionally the modifiers each form gives do not seem to be properly removed.

**Comment by Dli42** [comment]
I"ll work on this, Noya has more important stuff to figure out

**Comment by Dli42** [comment]
So the Normal Form spell literally does nothing right now. I'm going to remove it and just have the other toggles. What should be the cooldown on changing forms?

**Comment by Vendivar** [comment]
Yeah I considered this and I think normal form is important to at least denote which form you are currently in.

**Comment by Vendivar** [comment]
The cooldown is about 5 seconds for each
