### ISSUE TITLE
Shapeshifter ability hotkeys are inconsistent

### ISSUE THREAD

**Issue by Dli42** [Vendivar/IslandTrollTribes2#172]
The three toggle abilities move around all over the place as abilities are added/removed. I'm not sure how to get them to stay still.

**Comment by MNoya** [comment]
Could probably be achieved by `SetAbilityIndex` and/or `SwapAbilities`

**Comment by Nooobody** [comment]
SetAbilityIndex doesn't have any documentation and it only takes 1 argument. 

SwapAbilities is kinda shady. The API documentation says: 

> "The ability order is never swapped when swapping abilities"

One thing to do would be to always have the toggle abilities at the start, I think that would only need some location changes in the KV. But then all the important spells would be at the end.

**Comment by Nooobody** [comment]
The correct function to use is caster:SetAbilityByIndex, which changes the ability's position. However, this method doesn't remove the old index, and merely duplicates the ability on the hotbar.

SwapAbilities did nothing.

**Comment by Nooobody** [comment]
Since noya added the code where the spellbook reorders the abilities, the shapeshifter toggle abilities are now Q,W,E when in normal form and E,D,F when in one of the forms. I believe it's good enough, so I'm closing this.
