### ISSUE TITLE
Gatherer Default Ping needs to exclude bushes.

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#174]

**Comment by MNoya** [comment]
I thought I fixed this on f73400de91ebad6260f843e1d5c6492e2afabed0 - Ping shouldn't be taking items that have "bush" in its name. Or is there another function tied to it?

**Comment by Vendivar** [comment]
It was fixed but because the bushes got turned into items we removed the filter to reuse it. Its an easy fix Dav has this one.
