### ISSUE TITLE
You can sell items on these spots

### ISSUE THREAD

**Issue by Exactuz** [Vendivar/IslandTrollTribes2#18]
![image](https://cloud.githubusercontent.com/assets/17887951/13827184/2422ec58-ebf6-11e5-980c-83db71e64c24.png)
![image](https://cloud.githubusercontent.com/assets/17887951/13864268/02a6be0c-ecdb-11e5-95b5-8583b8b2eb8b.png)

**Comment by MNoya** [comment]
Need to verify that this was tested using the correct map version

**Comment by Exactuz** [comment]
It is fixed now

**Comment by Vendivar** [comment]
This is a bug again for some reason probably has to do with me removing the blockers.

**Comment by Dli42** [comment]
Oh, it looks like that's where the boats despawn. For some reason the sell triggers are sticking there.

**Comment by MNoya** [comment]
Need to wait a bit more to spawn the boat triggers I think

**Comment by Dli42** [comment]
Yup, we should move the triggers off the map after it's boat despawns
