### ISSUE TITLE
Master Healer Replenish does not work

### ISSUE THREAD

**Issue by Dli42** [Vendivar/IslandTrollTribes2#182]
Ends by itself after a couple ticks.

I think this is due to health degen being coded as damage currently (because negative health regeneration doesn't work), so when your health ticks down from hunger it cancels the buff. We can work around this by setting a minimum damage threshold on canceling the buff.

**Comment by Vendivar** [comment]
Maybe another easy work around would be to remove the modifier that causes degen for the duration of this spell. Not sure how OP that would be though.
