### ISSUE TITLE
Chat needs to be added to the character select screen

### ISSUE THREAD

**Issue by Dli42** [Vendivar/IslandTrollTribes2#186]

**Comment by MNoya** [comment]
Part of #100 and pretty important

**Comment by Vendivar** [comment]
Crumbling Island Arena had it set up pretty nicely. Also if we opted to use their chat we could allow for custom names just like in ITT1.

https://github.com/DoctorGester/crumbling-island-arena/blob/master/content/panorama/scripts/custom_game/keybind_register.js
https://github.com/DoctorGester/crumbling-island-arena/blob/master/content/panorama/scripts/custom_game/game_hud.js
