### ISSUE TITLE
building control

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#220]
You lose control of the building if you select it and click the ground, can be frustrating when trying to pick up materials laying on the ground next to the building (you have to reselect the building if you misclick).

**Comment by MNoya** [comment]
This is intended from #104 but I understand how it can be a problem. Should we revert this @Vendivar ?

**Comment by Vendivar** [comment]
@muhshi4  Can we make it so instead it checks to make sure you double clicked the ground? Or would you think just pressing ESC would be best
