### ISSUE TITLE
Herbmaster cant craft potions in inventory

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#227]
The popup message "a mixing pot is required for crafting this" comes up when you try to use the crafting panel

**Comment by Nooobody** [comment]
This only happens if you use the crafting menu. When using the Mix ability, you can craft potions normally.

**Comment by Nooobody** [comment]
You can now either use the crafting menu, or the mix ability to craft the mixing pot recipes as a herbmaster.
