### ISSUE TITLE
When thistles are added to blowgun they get reduced to 3

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#229]
When trying to add a stack of 15 thistles to a blowgun only 3 is added.

If you craft darkthistles with 15 normal thistles you only recieve 1 dark thistle

**Comment by Nooobody** [comment]
Blowgun only takes 3 charges, so that's intentional.

The darkthistles doesn't seem to recognize the stack and uses all of them regardless of the stack size.
I will look into this.

**Comment by Nooobody** [comment]
Only one thistle is used now when crafting darkthistles.
