### ISSUE TITLE
Default Wearable Rework

### ISSUE THREAD

**Issue by MNoya** [Vendivar/IslandTrollTribes2#261]
The newly added API `FollowEntity` can be used in conjunction with KV "DisableWearables" on each hero in order to ensure the wearables are properly set even on dedicated servers.

**Comment by MNoya** [comment]
The new system would be dedi-friendly but needs custom portraits, because otherwise you get headless lycan and sexy-naked lion:

![img](https://puu.sh/qliRW/323fa51a36.jpg)
![img](https://puu.sh/qlix0/8cfbf3b5df.jpg)

**Comment by Vendivar** [comment]
How do we get custom portraits? Is there a way to use the web m files we
already have

**Comment by MNoya** [comment]
yeah using webm same as the panorama DotaHeroMovie panels we have on the picking screen

**Comment by Vendivar** [comment]
Where do I apply the webm to

**Comment by MNoya** [comment]
There's no way to easily change it (because the UI is scaleform) so it would need a panorama UI, either on top of the portrait (kinda weird and would clip with the HUD) or a whole new ability bar hud (ugh...)
