### ISSUE TITLE
Elks still run out of the map in some places

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#264]

**Comment by muhshi4** [comment]
just make a square of trees around the whole map?

**Comment by Vendivar** [comment]
There already is

**Comment by Vendivar** [comment]
I need specific locations of where they ran out

**Comment by muhshi4** [comment]
http://imgur.com/a/Dxp4w just search for places like this on the map

**Comment by muhshi4** [comment]
there's a invisible wall for the troll but the elks can run past it

**Comment by muhshi4** [comment]
there's a bunch of these in the map
