### ISSUE TITLE
Tannery model is too high, blocks a lot of space in base

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#290]
Remove the stuff on top of the tannery to make it smaller? same problem as with witch doctor hut

**Comment by muhshi4** [comment]
making every building about the same size as workshop would really help with this issue. Some of the buildings models are so big that you accidentally click on them.

**Comment by Vendivar** [comment]
http://forums.sideshopgames.com/thread-11.html
