### ISSUE TITLE
Some people can't open the craft menu

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#291]
There's a bug where some people can't open the craft menu and have to restart dota for it to work. When they rejoin the game crafting works but they cant open the chat window. at least 2 ppl have this bug every game.

**Comment by muhshi4** [comment]
ToggleCraftingList
!! (s2r://panorama/scripts/crafting/crafting_button.vjs_c, line:3, col:28) - TypeError: undefined is not a function

this is what console says

**Comment by Nooobody** [comment]
That error in the crafting button is just the aftermath.

The real reason for that lies at the beginning of the error list, because it fails to build the whole crafting list for some reason. I need that original error to fix it.
