### ISSUE TITLE
You can't pack fires placed by teammates

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#295]

**Comment by Nooobody** [comment]
We're there boats?

**Comment by muhshi4** [comment]
yeah

**Comment by muhshi4** [comment]
tested it in the newest patch, The guy who places the fire is the only one who can pack it up. Everyone on the same team should be able to pack it up.

**Comment by Vendivar** [comment]
I had this designed that way to prevent griefing from teammates
