### ISSUE TITLE
Change river root model

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#298]
It's impossible to see it when dropped on water and barely visible when on the ground.

**Comment by muhshi4** [comment]
or make it more visible or bigger

**Comment by Vendivar** [comment]
Can I get a pic of the original itt1 model used so I can think about how to
remake it

**Comment by muhshi4** [comment]
change the color of the river stem to blue and name it river root

**Comment by muhshi4** [comment]
Change the model to the same as river stem but make it blue, that's an easy solution, no?

**Comment by muhshi4** [comment]
http://imgur.com/a/JlG7H here's a pic of the wc3 one

**Comment by Vendivar** [comment]
I'll see what I can do. It's easier for me to make new models now
