### ISSUE TITLE
Smoke house is bugged

### ISSUE THREAD

**Issue by Exactuz** [Vendivar/IslandTrollTribes2#30]
Smoke meat skill just eats meat. Rightclicking on smoke house causes transport ship window to pop up.
![image](https://cloud.githubusercontent.com/assets/17887951/13899870/6136ebfa-ee33-11e5-8d60-45a41a12591f.png)

**Comment by MNoya** [comment]
Issue should be resolved, it's implemented now. Couple further additions might be required:

@Vendivar this only currently only considers the meat from inventory and places it on the inventory

Would you like any of:

1. Check for cooked meat dropped in close radius?
2. Eject the meat from the inventory near the building?
3. Auto-cast usage?

**Comment by Vendivar** [comment]
Only auto cast usage for the meat in the inventory.
