### ISSUE TITLE
The living clay that scouts can pick up from scout bushes are super bugged

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#304]
They multiply into new items when you use them.

The amount of living clay doesn't go down when you use it, so you basically have unlimited living clays.

the living clays can block enemies when placed.

hostile animals start autoattacking the living clays when they're nearby.

**Comment by Nooobody** [comment]
http://i.imgur.com/t8RVYbN.jpg
This is how you will die in our next match.
