### ISSUE TITLE
Tsunami deals more damage than its supposed to

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#317]
It doesn't deal the 25 dmg/spell. Instead it deals more dmg/waves that hit the target. It should be a constant 25 dmg.

**Comment by Vendivar** [comment]
one of you specifically told me it was 25 per wave

**Comment by Vendivar** [comment]
It would be easier to just reduce the damage of the per wave damage at this point

**Comment by muhshi4** [comment]
Lol youre the one who decided to do 4 differnt waves? Why not just make one wave?

**Comment by Vendivar** [comment]
I didn't "decide" to do it like it was some creative decision., I wasn't even the one who programmed it in relax
