### ISSUE TITLE
Queued (Shift Click) Item Pickup doesn't work if Hero is stationary

### ISSUE THREAD

**Issue by LukeDeighton** [Vendivar/IslandTrollTribes2#318]
There is an issue if you shift click on an item for the first time and your hero is not moving then it fails to pick up the item. The Timer only triggers once if the hero is stationary, but behaves properly if you are moving and then shift click on an item for the first time (it will fire events every 0.1 seconds).

**Comment by Vendivar** [comment]
same as #22
