### ISSUE TITLE
Bypass new hero selection by using a force hero pick then using our custom hero selection

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#331]

**Comment by Vendivar** [comment]
This may also be an opportunity to revamp the hero selection into something new using the new dota scene panel  http://moddota.com/forums/discussion/1399/panorama-custom-dotascenepanel

**Comment by Vendivar** [comment]
It may be better to go that route to make way for player levels and selecting their goodies..

**Comment by Nooobody** [comment]
Forcepicking works fine, but I need to change everything to the HUD phase so they get loaded properly. Also crafting didn't like the new hero thing at all.

When I integrate the hero picking and gamemode voting screens, it might be better to cover up the whole screen so you can't see that it picked a hero for you in the background.

**Comment by Nooobody** [comment]
The foundation is done for the integration, just need to change some stuff around and I can push it.
