### ISSUE TITLE
There is something wrong with herbs, thistles, etc spawn ratios

### ISSUE THREAD

**Issue by Exactuz** [Vendivar/IslandTrollTribes2#34]
I played for an hour and all bushes i checked had 0-1

**Comment by Vendivar** [comment]
Are you saying 0-1 per stack?

**Comment by Exactuz** [comment]
i mean somewhere there was an herb, but most of bushes were empty after 1 hour of playing

**Comment by Oshan07** [comment]
This issue should have been fixed with the commit cd062c7111f938d40b13c0beda7f9f230b350df5 . Please verify and close.
