### ISSUE TITLE
Change heropick section of wrapper to teamchat

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#343]

**Comment by Nooobody** [comment]
Not sure how to separate them since the voting and heroselection are in the same screen technically.

Best option would be to use Tab to change the mode, but can we bind that?

**Comment by Vendivar** [comment]
Anything can be bound and unbound

**Comment by Nooobody** [comment]
Tab can now be used to toggle the mode. Applies to both heropick/voting chat and ingame chat as well.
