### ISSUE TITLE
Particles that show up for Huskar, Lion, Witch Doctor, and Dazzle's immortal cosmetic weapons need to be hidden.

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#56]

**Comment by MNoya** [comment]
We need to identify all the models with cosmetic particles and replace those by particle systems with all their childs disabled

**Comment by MNoya** [comment]
@Vendivar there's a new huskar set we should use: http://dota2.gamepedia.com/Reckless_Vigor

Here's the cosmetic particles that I found need to disable:
* Searing Dominator
* Infernal Wings Mace
* Fin King's Charm
* Gauntlet of the Treacherous Demon
* Bonkers the Mad
* Pipe of Dezun
* Darkclaw Emissary
* Lamb to the Slaughter + Golden version
* Shade of the Spiteful Eye (Ambient unlock)
* Most Shadow Shaman set weapons

Please if I miss any, let me know.

**Comment by Vendivar** [comment]
Thanks for getting the list. I don't see any set items missing. If there is
anything I'll follow the code and fill in the gaps. Also that husker set
looks good I'll see about reworking the useage of sets with it. Could be
great for tracker.
