### ISSUE TITLE
Multi Team Flyout Revamp

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#60]
The Multi-Team flyout scoreboard should be showing the values of the players heat / health (percent) / energy (percent) (for allied team only) as well as lining out their name and changing the color to black when they are dead.

**Comment by Fallexe** [comment]
Working on this one

**Comment by Fallexe** [comment]
Still needs name blackout

**Comment by MNoya** [comment]
I think showing the enemies heat, health and energy is problematic, isn't it?

**Comment by Vendivar** [comment]
Yes I explained that to him but I can update the description of the issue.
