### ISSUE TITLE
Victory endscreen should have a little proper fanfare

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#62]

**Comment by Vendivar** [comment]
I saw what crumbling arena had used and I'd like to expand on it possibly with the new panorama element where we display the victory team's trolls in the background.

**Comment by MNoya** [comment]
Panorama 3D panels can't make things dynamically, but putting the trolls on a section on the map and changing the map angle (in [PMP endscreen](http://puu.sh/oPX3o/784faf6e04.jpg)) could be done

**Comment by Vendivar** [comment]
That would be great!
