### ISSUE TITLE
Dementia runes still is not functional.

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#65]

**Comment by Oshan07** [comment]
@Dli42 Sorry I just noticed you have started working on this. The change I did was, I made the runes to unattach from the caster and move to the target. I hope it will make it easy for you to continue fixing the issue.

**Comment by Dli42** [comment]
Ha, I actually did the same, but hadn't committed it yet. It's still helpful though, thanks!
