### ISSUE TITLE
Game Modes

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#67]
https://docs.google.com/spreadsheets/d/1Et5JpXrn6HVZNYhsH0oslgCPRqY9seSeM6KAsCkacfI/edit?usp=sharing

**Comment by Vendivar** [comment]
Needs voting for these game modes to take place before the game starts.

**Comment by Vendivar** [comment]
Additionally needs some room for preset game modes.

**Comment by Exactuz** [comment]
You can make different maps with preset modes

**Comment by MNoya** [comment]
Keep in mind making extra maps with different modes takes extra file size space. I think there should just be a 9 (default) and 12 player map.

**Comment by MNoya** [comment]
Draft https://docs.google.com/drawings/d/1gdwU8jMFKSH8JIedKUvwBDzlXlr0YR8Iv_gAAONKcT8/edit

**Comment by kotarou** [comment]
Can we use a single map, and use region blockers to restrict the size /
portions of it? Might be a clean workaround to map size issues.

Draft looks good, but I think "Fast/Normal/Slow mode" may be better
replaced by a game speed selector, which populates the settings with
presets whenever a game-speed is selected.

**Comment by Vendivar** [comment]
The team size is something that is determined by the lobby which isn't
controlled through the game settings
