### ISSUE TITLE
Hatchery doesn't work properly

### ISSUE THREAD

**Issue by Exactuz** [Vendivar/IslandTrollTribes2#77]
-Hatchery building doesn't give a vision.
-Some "Hatchery transmutable" lables are missing.
-Hawk is not under player's control. (intended?)
-Hawk doesn't gather items.
-Hatchery content seem to not be affecting hawk's stats.
-Need to clarify what is "Hawk evolution" skill. (does nothing)

**Comment by Vendivar** [comment]
Need to clearly define each type of bonus ability that the hawk should get. Still needs gathering, inventory slots, and one more ability. Also need to define the different models for when you have more then 3 of a specific ingredient as I labeled it for example.
