### ISSUE TITLE
Buildings shouldn't be able to use items.

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#78]

**Comment by Vendivar** [comment]
Buildings should not be able to use items in general. As in for example a building throwing a spear, only omni tower should do that.Building eating meat item is another example of what shouldn't happen.

**Comment by MNoya** [comment]
We can just Mute them, right? `MODIFIER_STATE_MUTED`

**Comment by Vendivar** [comment]
Does this prevent using abilities?

**Comment by MNoya** [comment]
I don't think it should, its easy to try it by just adding the State to the ability_building: https://github.com/Vendivar/IslandTrollTribes2/blob/master/game/islandtrolltribes/scripts/npc/abilities/buildings/ability_building.txt#L15

**Comment by Vendivar** [comment]
It was that easy. Just need to figure out how to selectively enable it for the omni tower now.
