### ISSUE TITLE
Building drop range infinite 

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#87]
Buildings drop range seems to be broken for now and the drop range is infinite.

**Comment by Oshan07** [comment]
Maximum drop range for buildings was set to 800.
https://github.com/Vendivar/IslandTrollTribes2/blob/910200296669286e7db65cc23cda4c1c96d0be58/game/islandtrolltribes/scripts/vscripts/filters.lua#L190
