### ISSUE TITLE
Beastmaster pets arent splitting exp

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#89]

**Comment by MNoya** [comment]
Hmm I tried a grown bear pet killing an elk and I got experience. Do you mean killing the pets themselves doesn't give xp to the enemy team?

**Comment by Vendivar** [comment]
No.  Maybe I was observing the event wrong or there was some other
condition that was causing the bug

**Comment by MNoya** [comment]
When that happens, try to get a hold of the vscript error log, would be useful to see at which line it errored
