### ISSUE TITLE
Picking up a gold bag insta-crashes game

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#90]

**Comment by MNoya** [comment]
This worked on my test on tools (http://gfycat.com/FavoriteBigheartedAfricanrockpython), are we sure its the bag picking and not a side crash due to players dying?

**Comment by Vendivar** [comment]
To reproduce the issue I used a magic to Suicide upon responding picking up
the bag instantly crash my game

**Comment by Vendivar** [comment]
This seems to happen when you have 5000 gold from using dev
