### ISSUE TITLE
Error message css

### ISSUE THREAD

**Issue by MNoya** [Vendivar/IslandTrollTribes2#99]
Make it look like the dota error like it was before

**Comment by Vendivar** [comment]
I made a change in the CSS that I'm okay with. It's pretty close.

**Comment by Vendivar** [comment]
I made a change in the CSS that I'm okay with. It's pretty close.

**Comment by Vendivar** [comment]
I made a change in the CSS that I'm okay with. It's pretty close.

**Comment by Vendivar** [comment]
I made a change in the CSS that I'm okay with. It's pretty close.

**Comment by Vendivar** [comment]
I made a change in the CSS that I'm okay with. It's pretty close.

**Comment by MNoya** [comment]
I had the css of before, give a try if you don't like it just revert :smiley:
